name: Gradle Build and Checkstyle

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Clean and Build
        run: ./gradlew clean build

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain
